name: Upload to Telegram with Local Bot API

on:
  workflow_dispatch:
    inputs:
      date:
        description: 'Date in YYYYMMDD format (for daily) or "weekly-YYYYMMDD-to-YYYYMMDD" for weekly timelapse'
        required: true
        type: string

permissions:
  contents: read

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Determine upload type and parse dates
        id: upload-type
        run: |
          INPUT_DATE="${{ github.event.inputs.date }}"
          
          if [[ "$INPUT_DATE" == weekly-*-to-* ]]; then
            echo "type=weekly" >> $GITHUB_OUTPUT
            # Извлекаем даты из формата weekly-YYYYMMDD-to-YYYYMMDD
            WEEK_START=$(echo "$INPUT_DATE" | cut -d'-' -f2)
            WEEK_END=$(echo "$INPUT_DATE" | cut -d'-' -f4)
            echo "week_start=$WEEK_START" >> $GITHUB_OUTPUT
            echo "week_end=$WEEK_END" >> $GITHUB_OUTPUT
            echo "tag=weekly-timelapse-$WEEK_START-to-$WEEK_END" >> $GITHUB_OUTPUT
            echo "file_pattern=weekly_timelapse.mp4" >> $GITHUB_OUTPUT
            echo "output_file=weekly_timelapse_${WEEK_START}_to_${WEEK_END}.mp4" >> $GITHUB_OUTPUT
          else
            echo "type=daily" >> $GITHUB_OUTPUT
            echo "tag=timelapse-$INPUT_DATE" >> $GITHUB_OUTPUT
            echo "file_pattern=timelapse_$INPUT_DATE.mp4" >> $GITHUB_OUTPUT
            echo "output_file=timelapse_$INPUT_DATE.mp4" >> $GITHUB_OUTPUT
          fi

      - name: Format dates for message
        id: format-dates
        run: |
          if [ "${{ steps.upload-type.outputs.type }}" = "weekly" ]; then
            # Форматируем даты в человекочитаемый формат
            START_DATE="${{ steps.upload-type.outputs.week_start }}"
            END_DATE="${{ steps.upload-type.outputs.week_end }}"
            
            FORMATTED_START=$(echo "$START_DATE" | sed 's/\(....\)\(..\)\(..\)/\1-\2-\3/')
            FORMATTED_END=$(echo "$END_DATE" | sed 's/\(....\)\(..\)\(..\)/\1-\2-\3/')
            
            echo "formatted_start=$FORMATTED_START" >> $GITHUB_OUTPUT
            echo "formatted_end=$FORMATTED_END" >> $GITHUB_OUTPUT
          else
            DAILY_DATE="${{ github.event.inputs.date }}"
            FORMATTED_DAILY=$(echo "$DAILY_DATE" | sed 's/\(....\)\(..\)\(..\)/\1-\2-\3/')
            echo "formatted_daily=$FORMATTED_DAILY" >> $GITHUB_OUTPUT
          fi

      - name: Download timelapse from Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          TAG="${{ steps.upload-type.outputs.tag }}"
          FILE_PATTERN="${{ steps.upload-type.outputs.file_pattern }}"
          OUTPUT_FILE="${{ steps.upload-type.outputs.output_file }}"
          
          mkdir -p timelapse
          if gh release view "$TAG" --repo "$GITHUB_REPOSITORY" >/dev/null 2>&1; then
            echo "Found release $TAG, downloading asset"
            gh release download "$TAG" --repo "$GITHUB_REPOSITORY" --pattern "$FILE_PATTERN" --dir timelapse --clobber
            
            # Проверяем что файл скачался
            if [ -f "timelapse/$FILE_PATTERN" ]; then
              echo "✅ File downloaded: timelapse/$FILE_PATTERN"
              # Для недельного таймлапса может потребоваться переименование
              if [ "$FILE_PATTERN" != "$OUTPUT_FILE" ]; then
                mv "timelapse/$FILE_PATTERN" "timelapse/$OUTPUT_FILE"
                echo "✅ File renamed to: timelapse/$OUTPUT_FILE"
              fi
            else
              echo "❌ File $FILE_PATTERN not found in release"
              ls -la timelapse/
              exit 1
            fi
          else
            echo "❌ Release $TAG not found"
            echo "Available releases:"
            gh release list --repo "$GITHUB_REPOSITORY" --limit 10
            exit 1
          fi

      - name: Cache apt packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: make git zlib1g-dev libssl-dev gperf cmake g++
          version: 1

      - name: Cache TDLib source
        id: cache-tdlib
        uses: actions/cache@v4
        with:
          path: tdlib-source
          key: tdlib-source-${{ runner.os }}-latest
          restore-keys: |
            tdlib-source-${{ runner.os }}-

      - name: Cache Telegram Bot API server
        id: cache-bot-api
        uses: actions/cache@v4
        with:
          path: telegram-bot-api
          key: telegram-bot-api-${{ runner.os }}-built
          restore-keys: |
            telegram-bot-api-${{ runner.os }}-

      - name: Log cache status
        run: |
          echo "=== Статус кэша ==="
          echo "TDLib cache hit: ${{ steps.cache-tdlib.outputs.cache-hit }}"
          echo "Bot API cache hit: ${{ steps.cache-bot-api.outputs.cache-hit }}"
          
          if [ "${{ steps.cache-tdlib.outputs.cache-hit }}" = "true" ]; then
            echo "✅ TDLib восстановлен из кэша"
          else
            echo "🔄 TDLib будет собран заново"
          fi
          
          if [ "${{ steps.cache-bot-api.outputs.cache-hit }}" = "true" ]; then
            echo "✅ Bot API восстановлен из кэша"
          else
            echo "🔄 Bot API будет собран заново"
          fi

      - name: Get TDLib source
        if: steps.cache-tdlib.outputs.cache-hit != 'true'
        run: |
          # Очищаем папку если она существует
          rm -rf tdlib-source
          # Клонируем репозиторий TDLib с конкретной версией
          git clone --recursive https://github.com/tdlib/td.git tdlib-source
          cd tdlib-source
          # Переключаемся на стабильную версиею
          git checkout v1.8.0
          # Очищаем git history для кэширования
          rm -rf .git
          cd ..

      - name: Build Telegram Bot API server
        if: steps.cache-bot-api.outputs.cache-hit != 'true'
        run: |
          # Очищаем папку если она существует
          rm -rf telegram-bot-api
          # Клонируем репозиторий Bot API с конкретной версией
          git clone --recursive https://github.com/tdlib/telegram-bot-api.git
          cd telegram-bot-api
          # Проверяем доступные теги и используем последний стабильный
          git fetch --tags
          LATEST_TAG=$(git describe --tags --abbrev=0)
          echo "Using tag: $LATEST_TAG"
          git checkout $LATEST_TAG
          
          # Создаем и переходим в build директорию
          rm -rf build
          mkdir build
          cd build
          
          # Конфигурируем и собираем (используем кэшированные исходники TDLib)
          cmake -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_INSTALL_PREFIX:PATH=.. \
                -DTD_DIR=../../tdlib-source \
                ..
          cmake --build . --target install
          
          # Возвращаемся в корень
          cd ../..
          
          # Проверяем что бинарник создался
          ls -l telegram-bot-api/bin/telegram-bot-api*

      - name: Setup Bot API server
        run: |
          # Создаем директорию для данных
          mkdir -p bot-data
          
          # Проверяем что у нас есть (из кэша или свежесобранное)
          echo "=== Проверка доступных файлов ==="
          if [ -d "telegram-bot-api/bin" ]; then
            echo "✅ Bot API найден в кэше/собран"
            ls -la telegram-bot-api/bin/
          else
            echo "❌ Bot API не найден"
            exit 1
          fi
          
          if [ -d "tdlib-source" ]; then
            echo "✅ TDLib найден в кэше"
            ls -la tdlib-source/ | head -5
          else
            echo "❌ TDLib не найден"
            exit 1
          fi

      - name: Start local Bot API server
        run: |
          # Запускаем локальный сервер в фоне
          ./telegram-bot-api/bin/telegram-bot-api --api-id=${{ secrets.TELEGRAM_API_ID }} \
                            --api-hash=${{ secrets.TELEGRAM_API_HASH }} \
                            --local \
                            --dir=./bot-data \
                            --temp-dir=./bot-data/temp \
                            --http-port=8081 &
          
          # Ждем пока сервер запустится
          sleep 10
          
          # Проверяем что сервер работает
          curl -f http://localhost:8081/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/getMe || exit 1

      - name: Check if timelapse exists
        id: check
        run: |
          OUTPUT_FILE="${{ steps.upload-type.outputs.output_file }}"
          if [ -f "timelapse/$OUTPUT_FILE" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "file_size=$(stat -f%z timelapse/$OUTPUT_FILE 2>/dev/null || stat -c%s timelapse/$OUTPUT_FILE)" >> $GITHUB_OUTPUT
            echo "✅ File found: timelapse/$OUTPUT_FILE"
            ls -la "timelapse/$OUTPUT_FILE"
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "❌ File not found: timelapse/$OUTPUT_FILE"
            ls -la timelapse/
            exit 1
          fi

      - name: Upload to Telegram
        if: steps.check.outputs.exists == 'true'
        run: |
          OUTPUT_FILE="${{ steps.upload-type.outputs.output_file }}"
          VIDEO_FILE="timelapse/$OUTPUT_FILE"
          
          if [ "${{ steps.upload-type.outputs.type }}" = "weekly" ]; then
            # Сообщение для недельного таймлапса с датами
            MESSAGE=$(echo -e "📅 Недельный таймлапс с ${{ steps.format-dates.outputs.formatted_start }} по ${{ steps.format-dates.outputs.formatted_end }}\n\n[🎬 Репозиторий с автоматизироваными таймлапсами](https://github.com/niklinque/wplace-tomsk-timelapse/)\n[📸 Репозиторий с дампами](https://github.com/niklinque/wplace-tomsk/)")
            
            echo "Uploading weekly timelapse: $MESSAGE"
            
            # Для недельного таймлапса отправляем как видео
            curl -X POST "http://localhost:8081/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendDocument" \
                 -F "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
                 -F "document=@${VIDEO_FILE}" \
                 -F "caption=${MESSAGE}" \
                 -F "parse_mode=MARKDOWN" \
                 --max-time 1800 \
                 --retry 3 \
                 --retry-delay 30
          else
            # Сообщение для ежедневного таймлапса
            MESSAGE=$(echo -e "🤖 Ежедневный таймлапс за ${{ steps.format-dates.outputs.formatted_daily }}\n\n[🎬 Репозиторий с автоматизироваными таймлапсами](https://github.com/niklinque/wplace-tomsk-timelapse/)\n[📸 Репозиторий с дампами](https://github.com/niklinque/wplace-tomsk/)")
            
            echo "Uploading daily timelapse: $MESSAGE"
            
            # Для ежедневного отправляем как документ (поддерживает файлы до 2GB)
            curl -X POST "http://localhost:8081/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendDocument" \
                 -F "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
                 -F "document=@${VIDEO_FILE}" \
                 -F "caption=${MESSAGE}" \
                 -F "parse_mode=MARKDOWN" \
                 -F "disable_content_type_detection=true" \
                 --max-time 1800 \
                 --retry 3 \
                 --retry-delay 30
          fi

      - name: Cleanup
        if: always()
        run: |
          # Останавливаем сервер Bot API
          pkill -f telegram-bot-api || true
          # Очищаем временные файлы
          rm -rf timelapse/ bot-data/ || true